function players = getPlayerInit()
    %GETPLAYERINIT Summary of this function goes here
    %   Detailed explanation goes here
    players = zeros([8,1]);
    for id=1:8
        team = struct('a',1,'b',2);
        pos = [[0.5,3], ...
               [1.9,3], ...
               [3.5,4], ...
               [3.3,2], ...
               [5.7,4], ...
               [5.7,2], ...
               [7.1,2], ...
               [8.5,3]];
        role = [1, 2, 3, 0, 0, 3, 2, 1];%0=attacker, 2,3=defender, 1=goal keeper
        player = struc('id', id, ...
                       'team', team((id>4)+1), ...
                       'pos', pos(id), ...
                       'vel', [0,0], ...
                       'role', role(id), ...
                       'dir', pi-pi*(id<=4), ...
                       'lastKick', -1);
        players(id) = player;
    end

end

