
player(1:4) = struct('id', {1,2,3,4}, ...
                     'name', {'A1', 'A2', 'A3', 'A4'}, ...
                     'team', {'A', 'A', 'A', 'A'}, ...
                     'position', {[0, 0], [2, 0], [0, 2], [-2, 0]}, ...
                     'velocity', {[0, 0], [0, -1], [1, 1], [-1, 0]}, ...
                     'role', {'striker', 'defender', 'defender', 'goalkeeper'}, ...
                     'direction', 0, ...
                     'last_kick', 0);

player(5:8) = struct('id', {5,6,7,8,}, ...
                     'name', {'B5', 'B6', 'B7', 'B8'}, ...
                     'team', {'B', 'B', 'B', 'B'}, ...
                     'position', {[0, 0], [-2, 0], [0, -2], [2, 0]}, ...
                     'velocity', {[0, 0], [0, 1], [-1, -1], [1, 0]}, ...
                     'role', {'striker', 'defender', 'defender', 'goalkeeper'}, ...
                     'direction', pi, ...
                     'last_kick', 0);